services:
  backend:
    image: countries-image
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment: POSTGRES_USER= countries_user
      POSTGRES_PASSWORD= countries_password
      POSTGRES_DB= countries_database
